# This is a basic workflow to help you get started with Actions

name: CI-Geometry

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:    
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.4.1'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project test/runtests.jl
